spring.application.name=elms
spring.datasource.url=jdbc:mysql://localhost:3306/elms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Lsf121212@
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

cloudinary.cloud-name=duddqeeeh
cloudinary.api-key=694258131245138
cloudinary.api-secret=eF8Zhsz05KkKiJvVXoBRZY1ijXI

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

server.error.include-message=always
server.error.include-binding-errors=always