spring.application.name=elms
spring.datasource.url=jdbc:mysql://localhost:3307/elms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=test123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true